name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set tag name to vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=Release

    - name: Build project
      run: msbuild /p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: ClipboardHistoryMerger-${{  steps.vars.outputs.tag }}
        path: ./clipboard-history-merger/src/bin/Release/*

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./clipboard-history-merger/src/bin/Release/*
        asset_name: ClipboardHistoryMerger-${{  steps.vars.outputs.tag }}.zip
        asset_content_type: application/zip
