name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set tag name to vars
      id: vars
      run: |
        echo "artifact=ClipboardHistoryMerger.zip" >> $GITHUB_OUTPUT
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=Release

    - name: Build project
      run: msbuild /p:Configuration=Release
      
    - name: Compress artifact
      run: Compress-Archive -Path ./src/bin/Release/* -Destination ${{ steps.vars.outputs.artifact }}

    - uses: actions/upload-artifact@v2
      with:
        path: ./${{ steps.vars.outputs.artifact }}

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./${{ steps.vars.outputs.artifact }}
        
